### ISSUE TITLE
No such file or directory: 'README.rst'

### ISSUE THREAD

**Issue by inactinique** [llefebure/dynamic_bernoulli_embeddings#1]
* dynamic_bernoulli_embeddings version: git master
* Python version: 3.8.2
* Operating System: ubuntu 20.04

### Description

I was trying to install dynamic_bernouilli_embeddings with the command line: 
pip3 install git+git://github.com/llefebure/dynamic_bernoulli_embeddings.git

### What I Did

```
Collecting git+git://github.com/llefebure/dynamic_bernoulli_embeddings.git
  Cloning git://github.com/llefebure/dynamic_bernoulli_embeddings.git to /tmp/pip-req-build-zpwfyzir
  Running command git clone -q git://github.com/llefebure/dynamic_bernoulli_embeddings.git /tmp/pip-req-build-zpwfyzir
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-zpwfyzir/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-zpwfyzir/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-zpwfyzir/pip-egg-info
         cwd: /tmp/pip-req-build-zpwfyzir/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-zpwfyzir/setup.py", line 7, in <module>
        with open("README.rst") as readme_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by llefebure** [comment]
Thanks @inactinique ! Should be fixed now.

**Comment by inactinique** [comment]
Thanks, installs perfectly now!
