### ISSUE TITLE
RuntimeError in model backward

### ISSUE THREAD

**Issue by xixi019** [llefebure/dynamic_bernoulli_embeddings#4]
* dynamic_bernoulli_embeddings version: git master
* Python version: Python 3.7.13
* Operating System: Linux

### Description

I was trying to train the model on PubMed Medline data. 
While i was running: python main.py
The model is supposed to take the processed data and start training.
However there is a runtime error while the code runs to the loss.backward() line:

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Python main.py
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    dataset, dictionary.token2id, validation=.1, num_epochs=6, k=100)
  File "/informatik2/sems/home/yan/isws/training.py", line 96, in train_model
    loss.backward()
  File "/export/home/yan/anaconda3/envs/isws/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/export/home/yan/anaconda3/envs/isws/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: unique_by_key: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```
Many thanks

**Comment by xixi019** [comment]
I have checked, the data and model are saved in cuda.
